### ISSUE TITLE
How do I run it?

### ISSUE THREAD

**Issue by adamavenir** [bryan1anderson/iMessage-to-Day-One-Importer#3]
Hey! This looks super cool :) 

I'm unfamiliar with running this type of project. How exactly do I run it?

**Comment by davisonio** [comment]
me too @bryan1anderson

**Comment by bryan1anderson** [comment]
Download Xcode. Open the Workspace file. 

Build it using the Play button
![screen shot 2018-04-25 at 1 55 39 pm](https://user-images.githubusercontent.com/7976521/39269545-5bf95542-4890-11e8-9eff-56a3fdbf20d7.png)


Then run it with the tool bar icon once its finished building

![screen shot 2018-04-25 at 1 55 55 pm](https://user-images.githubusercontent.com/7976521/39269569-74f17638-4890-11e8-8bb8-01c30b7ecc96.png)

**Comment by adamavenir** [comment]
Confirming this runs the app and closing the issue :)
